### ISSUE TITLE
A bug?! in `get_next_segment` or `best_link` function

### ISSUE THREAD

**Issue by SarahAlidoost** [CityRiverSpaces/rcoins#20]
in #19, we are implementing `from_edge` option for `stroke` function. According to the test below, the expected stroke is the red line:
```r
test_that("strokes can be formed starting from a given edge", {
  new_l1 <- sf::st_linestring(c(p1, p2, p3))
  sfc <- sf::st_sfc(new_l1, l4, l7)
  # p1 - p2 - p3
  #         \
  #           p5 - p6
  expected <- sf::st_sfc(sf::st_linestring(c(p1, p2, p5, p6)))
  actual <- stroke(sfc, flow_mode = FALSE, from_edge = list(3))
  expect_setequal(actual, expected)
})
```
![sfc](https://github.com/user-attachments/assets/6c33e2ff-13a7-407f-abfe-d513fa2b634c)
However, the `best_links` table shows that l3 includes s1, see `[3,]     1   4`, but l1 doesnot include s3, see `[1,]    NA   2`. 
```r
> best_links
     start end
[1,]    NA   2
[2,]     1  NA
[3,]     1   4
[4,]     3  NA
```
The values (NA   2) will be returned by the function `get_next_segment` which is a length of two. This is an issue. One way to fix this has been implemented [here](https://github.com/CityRiverSpaces/rcoins/blob/89d7e38c1016b8fabd9416547cdf26caee1fc317/R/stroke.R#L250-L252), assuming that if a link does not include a segment, the `get_next_segment` should return `NA`. But I am not sure if this is the best solution.

**Comment by fnattino** [comment]
Thanks for raising the issue! I had a look at it in a bit more detail and I am afraid the solution might be a bit more involved. 

So, in the search for strokes in the general case (so when `from_edge` is NULL), the links are reciprocal (if link A is connected to B, B is connected to A). I have implemented this with the `get_next_segment` function, which should find the segment that continues the current one via a given link. However, this was somehow relying on the reciprocity of linking: starting from segment A, `get_next_segment` considers its link B and checks which segments B is connected to; these segments will be A and a third segment C, so I could discard A (since that is the segment where one is coming from), and only consider C as continuation. 

But when setting `from_edge`, we drop the reciprocity requirements. So, in your example, you consider segment 3,  take segment 1 as link and try to find the continuation. Since segment 1 does not list segment 3 as a link, `get_next_segment` return both "NA" (end-point) and segment 2 as potential continuations - hence the issue..

Not sure right now what the solution might be, I will give it some thoughts..
